name: bibletree
description: 'Bible Tree'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.2.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_local_notifications: ^18.0.1
    go_router: ^14.2.7
    implicitly_animated_list: ^2.2.0
    intl: ^0.19.0
    path: ^1.8.3
    path_provider: ^2.1.4
    provider: ^6.1.2
    shared_preferences: ^2.2.3
    sqflite: ^2.3.0
    timezone: ^0.10.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/verses.json
    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard-Thin.otf
                weight: 100
              - asset: assets/fonts/Pretendard-ExtraLight.otf
                weight: 200
              - asset: assets/fonts/Pretendard-Light.otf
                weight: 300
              - asset: assets/fonts/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard-Bold.otf
                weight: 700
              - asset: assets/fonts/Pretendard-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/Pretendard-Black.otf
                weight: 900
